<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>SmartDocumentSearch</AssemblyName>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="*" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="*" />
    <PackageReference Include="PdfPig" Version="*" />
    <PackageReference Include="Tesseract" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>